; RisenFontScale
; After modifying Scale, restart the game
; fonts that have already been created/cached will not resize in real time.
[FontScale]
; Enable/disable font scaling
Enabled=1
; Font scaling factor, 1.25 = enlarge by 25%
Scale=1.25
; Minimum font size after scaling (absolute value)
MinAbsHeight=6
; Maximum font size after scaling (absolute value)
MaxAbsHeight=96
; Enable/disable logging (1=enable 0=disable)
LogEnabled=0
; Log only the first N font creations (set to 0 to disable detailed logging)
LogFirstN=64

; If you want a borderless fullscreen, you can use Borderless Gaming  
; If you don't want to download other software, you can use the plugin below  
; Since you've already installed this, it means the dependencies are ready:  
;       https://github.com/Kanadeforever/BorderLimited/releases/latest
